use cargo_lock::Lockfile;

fn main() {
    let lock = Lockfile::load("Cargo.lock").unwrap();
    let hormone = lock.packages.iter()
        .find(|p| p.name.as_str() == "hormone")
        .unwrap();

    println!("cargo:rerun-if-changed=src/generated.rs");
    std::fs::write(
        "src/generated.rs",
        format!(
            "\
// This file is automatically generated during compilation
// and shall be excluded from source control.

pub static HORMONE_VERSION: &'static str = \"{}\";

",
            hormone.version
        )).unwrap();

}

